language: php

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0

install:
    - composer install --no-interaction --prefer-source

script:
    - vendor/bin/tester -p php $COVERAGE tests/ -s -c tests/php.ini

services:
    - mysql
