language: php

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

install:
    - composer install --no-interaction --prefer-source

script:
    - vendor/bin/tester -p php $COVERAGE tests/ -s -c tests/php.ini
    - vendor/bin/phpcs --standard=ruleset.xml --extensions=php,phpt --encoding=utf-8 --tab-width=4 -sp src tests

services:
    - mysql
